[project]
name = "pixo-analysee"
version = "0.1.0"
description = "画像処理・解析のテスト"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.2.6",
    "opencv-python>=4.12.0.88",
]
